# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chriswagnerblog.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Chris Wagner's Blog
  avatar: avatar.png
  gravatar: "8ad6d9d337bb91e211a72a6745e2d9b9" # Email MD5 hash
  description: "A magical blog experience" # used by search engines

  # Header and footer text
  # header_text: >
  #    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  #
  #   <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>
  # header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: eelhovercraft@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "cawagner"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam: "eelhovercraft"
  tumblr: 
  twitter: "chris_a_wagner"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-63133115-1"
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read full post"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
